# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MQTT configuration
mqtt:
  sensor:
    - name: "BMS Raw Data"
      state_topic: "homeassistant/sensor/bms_raw"
      value_template: "{{ value }}"
      unit_of_measurement: "raw"

    - name: "BMS Voltage"
      state_topic: "homeassistant/sensor/bms_raw"
      value_template: "{{ value[-3:] }}" # Extract the last 3 characters
      unit_of_measurement: "V"
