name: "Gobel Battery Monitor"
description: "Battery Monitor supports various BMS - Home Assistant Addon"
version: "1.5.0"
slug: "gobel_battery_monitor"
url: "https://github.com/fancyui/Gobel-Battery-HA-Addon"
init: false
homeassistant_api: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

panel_icon: "mdi:home-battery"

options:
  host_name: homeassistant
  mqtt_broker: homeassistant.local
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  device_name: "Gobel Monitor"
  battery_manufacturer: "Gobel Power"
  battery_model: "GP-SR1-PC200"
  max_parallel_allowed: 16
  connection_type: ""
  battery_port: "rs232"
  bms_type: "PACE_LV"
  bms_ip_address: "10.0.0.5"
  bms_ip_port: 9999
  bms_usb_port: "/dev/ttyUSB0"
  bms_baud_rate: 115200
  data_refresh_interval: 5
  debug: 0
  if_random: 0
schema:
  host_name: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  device_name: str
  battery_manufacturer: str
  battery_model: str
  max_parallel_allowed: int
  connection_type: list(ethernet|wifi|serial)
  battery_port: list(rs232|rs485)
  bms_type: list(PACE_LV|JK_ESS|RN200)
  bms_ip_address: str
  bms_ip_port: int
  bms_usb_port: str
  bms_baud_rate: int
  data_refresh_interval: int
  debug: int
  if_random: int
