name: "Gobel Pace BMS Monitor"
description: "Gobel Pace BMS Monitor"
version: "1.1.16"
slug: "gobel_pace_bms_monitr"
url: "https://github.com/fancyui/HomeAssistant-PaceBMS-Addon"
init: false
homeassistant_api: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true
ingress: true

panel_icon: "mdi:home-battery"

options:
  mqtt_broker: homeassistant.local
  mqtt_port: 1883
  mqtt_username: gobel
  mqtt_password: "123456"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  device_name: "gobel"
  connection_type: ""
  battery_port: "rs232"
  bms_brand: "PACE"
  bms_ip_address: "10.0.0.5"
  bms_ip_port: 9999
  bms_usb_port: "/dev/ttyUSB0"
  bms_baud_rate: 115200
  data_refresh_interval: 5
  debug: 0
schema:
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  device_name: str
  connection_type: list(ethernet|wifi|serial)
  battery_port: list(rs232|rs485)
  bms_brand: list(PACE|JK-ESS|RN200)
  bms_ip_address: str
  bms_ip_port: int
  bms_usb_port: str
  bms_baud_rate: int
  data_refresh_interval: int
  debug: int
